version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1524577640
layout:
  /header/:
    -
      - 'logo-9745 30'
      - 'spacer-3889 70'
  /main/:
    -
      - system-messages-9700
    -
      - system-content-8447
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3752 40'
      - 'spacer-6361 30'
      - 'branding-2234 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
