name: '16'
timestamp: 1526663239
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1524577640
positions:
  header: Header
  coming-soon: 'Module Position'
  header-slider: 'Module Position'
  breadcrumbs: Breadcrumbs
sections:
  header: Header
  navigation: Navigation
  project: Project
  results: Results
  topline: Topline
  partners: Partners
  bottomline: Bottomline
  synergies: Synergies
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-3033: Header
    position-position-8433: 'Module Position'
    position-position-1400: 'Module Position'
    position-position-2149: Breadcrumbs
  messages:
    system-messages-5789: 'System Messages'
  content:
    system-content-6976: 'Page Content'
  mobile-menu:
    mobile-menu-6245: Mobile-menu
inherit:
  default:
    position-position-3033: position-header
    position-position-1400: position-position-9913
    offcanvas: offcanvas
    mobile-menu-6245: mobile-menu-2992
  15:
    position-position-2149: position-position-5613
    system-messages-5789: system-messages-2330
    system-content-6976: system-content-3721
    subfeature: subfeature
