version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1524577640
layout:
  /header/:
    -
      - position-position-3033
    -
      - position-position-8433
    -
      - position-position-1400
  /navigation/: {  }
  /project/: {  }
  /results/: {  }
  /topline/: {  }
  /partners/: {  }
  /bottomline/: {  }
  /synergies/: {  }
  /feature/: {  }
  /main/:
    -
      - position-position-2149
    -
      - system-messages-5789
    -
      - system-content-6976
  subfeature: {  }
  /footer/: {  }
  offcanvas: {  }
structure:
  header:
    attributes:
      boxed: '2'
      class: ''
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  project:
    type: section
    attributes:
      boxed: ''
      class: ''
  results:
    type: section
    attributes:
      boxed: ''
      class: ''
  topline:
    type: section
    attributes:
      boxed: '2'
      class: ''
  partners:
    type: section
    attributes:
      boxed: ''
      class: ''
  bottomline:
    type: section
    attributes:
      boxed: '2'
      class: ''
  synergies:
    type: section
    attributes:
      boxed: ''
      class: ''
  feature:
    type: section
    attributes:
      boxed: '2'
      class: ''
  main:
    attributes:
      boxed: ''
      class: ''
  subfeature:
    type: section
    inherit:
      outline: '15'
      include:
        - attributes
        - block
        - children
  footer:
    attributes:
      boxed: ''
      class: ''
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  position-position-3033:
    title: Header
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: position-header
  position-position-8433:
    title: 'Module Position'
    attributes:
      key: coming-soon
  position-position-1400:
    title: 'Module Position'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: position-position-9913
  position-position-2149:
    title: Breadcrumbs
    inherit:
      outline: 15
      include:
        - attributes
        - block
      particle: position-position-5613
  system-messages-5789:
    inherit:
      outline: 15
      include:
        - attributes
        - block
      particle: system-messages-2330
  system-content-6976:
    inherit:
      outline: 15
      include:
        - attributes
        - block
      particle: system-content-3721
