name: _body_only
timestamp: 1524577642
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1524577640
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-2843: 'System Messages'
  content:
    system-content-1996: 'Page Content'
inherit: {  }
